"use client";

import { TextShimmer } from "@sapira/ui";

export default function TextShimmerPage() {
  return (
    <div className="space-y-10">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">TextShimmer</h1>
        <p className="text-muted-foreground mt-2">
          An AI-style shimmer gradient that sweeps across text. Perfect for loading states and AI-generated content indicators.
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold">Heading</h2>
        <TextShimmer className="text-4xl font-bold">
          AI-Powered Insights
        </TextShimmer>
      </section>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold">Loading State</h2>
        <div className="rounded-lg border p-6 space-y-2">
          <TextShimmer className="text-sm">
            Generating response...
          </TextShimmer>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold">Custom Duration &amp; Spread</h2>
        <div className="space-y-3">
          <TextShimmer duration={1} spread={1} className="text-xl font-semibold block">
            Fast &amp; tight shimmer
          </TextShimmer>
          <TextShimmer duration={4} spread={3} className="text-xl font-semibold block">
            Slow &amp; wide shimmer
          </TextShimmer>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-lg font-semibold">Inline Usage</h2>
        <p className="text-lg">
          This report was <TextShimmer className="font-semibold">generated by AI</TextShimmer> and may need review.
        </p>
      </section>
    </div>
  );
}
